import type { Product } from '@/types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Humus de Lombriz Premium',
    slug: 'humus-de-lombriz-premium',
    description: 'El mejor fertilizante orgánico para tus plantas.',
    longDescription: 'Nuestro Humus de Lombriz Premium es un fertilizante 100% orgánico, rico en nutrientes y microorganismos que mejoran la salud del suelo y promueven un crecimiento vigoroso de las plantas. Ideal para todo tipo de cultivos, desde hortalizas hasta plantas ornamentales.',
    price: 150.0,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'soil bag',
    category: 'Fertilizantes',
  },
  {
    id: '2',
    name: 'Pie de Cría (Lombriz Roja)',
    slug: 'pie-de-cria-lombriz-roja',
    description: 'Inicia tu propia vermicompostera con lombrices de alta calidad.',
    longDescription: 'El Pie de Cría contiene una mezcla de lombrices rojas californianas en todas sus etapas de desarrollo, junto con el sustrato en el que viven. Es la forma perfecta de empezar tu propia producción de humus en casa y reciclar tus desechos orgánicos.',
    price: 350.0,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'worm compost',
    category: 'Lombrices',
  },
  {
    id: '3',
    name: 'Lombriz Roja (por Litro)',
    slug: 'lombriz-roja-por-litro',
    description: 'Lombrices por volumen para grandes proyectos.',
    longDescription: 'Para proyectos de mayor escala, ofrecemos Lombriz Roja Californiana por litro. Esta opción es ideal para agricultores y paisajistas que buscan mejorar grandes extensiones de suelo de manera eficiente y sostenible.',
    price: 200.0,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'worms soil',
    category: 'Lombrices',
  },
  {
    id: '4',
    name: 'Lombriz Roja (por Pieza)',
    slug: 'lombriz-roja-por-pieza',
    description: 'Compra la cantidad exacta de lombrices que necesitas.',
    longDescription: 'Si tienes un proyecto pequeño o simplemente quieres añadir más lombrices a tu compostera, puedes comprarlas por pieza. Garantizamos lombrices sanas y activas, listas para trabajar en tu suelo.',
    price: 2.5,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'earthworm hand',
    category: 'Lombrices',
  },
  {
    id: '5',
    name: 'Kit de Vermicompostaje',
    slug: 'kit-de-vermicompostaje',
    description: 'Todo lo que necesitas para empezar a compostar en casa.',
    longDescription: 'Nuestro kit completo incluye una vermicompostera de fácil montaje, un pie de cría de lombriz roja, ropa de cama y una guía detallada para que comiences a reciclar tus residuos orgánicos y producir tu propio fertilizante de alta calidad sin complicaciones.',
    price: 1200.0,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'gardening kit',
    category: 'Kits',
  },
  {
    id: '6',
    name: 'Té de Humus de Lombriz',
    slug: 'te-de-humus-de-lombriz',
    description: 'Fertilizante líquido concentrado para una rápida absorción.',
    longDescription: 'El Té de Humus de Lombriz es un fertilizante líquido y bioestimulante que se aplica directamente a las plantas. Sus nutrientes son absorbidos rápidamente, resultando en un follaje más verde, mayor floración y frutos más sabrosos. Es ideal para todo tipo de plantas y se puede aplicar foliarmente o en el riego.',
    price: 90.0,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'liquid fertilizer',
    category: 'Fertilizantes',
  },
];
